name: Update README.md Daily on Changes to save.md

on:
  push:
    paths:
      - 'save.md'
  pull_request:
    paths:
      - 'save.md'
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Read data from save.md and update README.md
        run: |
          # Read data from save.md
          save_data=$(cat save.md)

          # Save the data to README.md
          echo "$save_data" > README.md

          # Append README.md with today's date
          today_date="### 🕒 Last Updated:  $(date +'%d %b %Y')"
          echo -e "\n$today_date" >> README.md

          # Commit and push the changes
          git add README.md
          git commit -m "Update README with data from save.md and today's date" || exit 0
          git push
