name: Update README.md Daily

on:
  push:
    paths:
      - 'README.md'

  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "NeerajLoveCyber"
          git config --global user.email "actions@github.com"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Update README with the current date (IST)
        run: |
          current_date=$(TZ="Asia/Kolkata" date '+%Y-%m-%d')
          sed -i "s|<!-- DATE -->|Last Updated (IST): $current_date|" README.md
          git add README.md
          git commit -m "Update README with the current date" || exit 0
          git push
