name: Update README.md Daily

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Update README with the current date
        run: |
          current_date=$(date)
          sed -i "s|<!-- DATE -->|Last Updated: $current_date|" README.md
          git add README.md
          git commit -m "Update README with the current date" || exit 0
          git push
